# encoding: UTF-8

require 'treetop'

require 'ptolemy/nodes'
require 'ptolemy/exceptions'

module Ptolemy

  # The main class that encapsulates all the parsing functionality.
  # It includes the parser generated by the treetop grammar.
  class Parser

    # Load TOML grammar into Treetop
    base_path = File.expand_path File.dirname(__FILE__)
    Treetop.load File.join(base_path, 'toml.tt')

    # Treetop would've generated a parser for TOML based on the grammar
    @@parser = TOMLParser.new

    # Verifies that the data is encoded in UTF-8 and that
    # the encoding is valid.
    # Parses the data using the {TOMLParser} generated by Treetop
    #
    # @param data [String] input to be parsed
    # @return [Hash] the input parsed into a ruby hash
    # @raise [ParseError] if there are encoding issues or parsing issues.
    def self.parse data
      # Data should be a valid UTF-8 encoded string.
      if data.encoding != Encoding::UTF_8
        raise ParseError, "Input is not UTF-8 encoded"
      end
      unless data.valid_encoding?
        raise ParseError, "Input contains invalid UTF-8 byte sequence"
      end

      tree = @@parser.parse data

      if tree.nil?
        raise ParseError, "Parse error at offset: #{@@parser.index}"
      end

      tree.to_value
    end

  end

end
